name: Publish Releases to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:
  pull_request:
    branches: [main, develop]
    paths:
      - ".github/workflows/build-package.yml"
      - ".github/workflows/publish-release.yml"

jobs:
  build-pkg:
    uses: ./.github/workflows/build-package.yml

  publish-release:
    name: Publish Release Package
    needs: build-pkg
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/project/rfdetr-plus/
    timeout-minutes: 10
    permissions:
      id-token: write
      contents: write # Add this line
    steps:
      - name: Download distribution artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - name: Display distribution files
        run: ls -lh dist/

      - name: Publish to PyPi
        if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          attestations: true

      - name: Upload assets to GitHub Release
        if: github.event_name == 'release'
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "dist/*"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
